export const characters = [
  {
    id: 1,
    name: "Ryuko Matoi",
    neighborhood: "Honnōji Academy",
    age: 17,
    image: "https://i.ibb.co/7rNGGzH/ryukomatoi.jpg",
  },
  {
    id: 2,
    name: "Ann Takamaki",
    neighborhood: "Yongen-Jaya",
    age: 16,
    image: "https://i.ibb.co/q9443D1/anntakamaki.jpg",
  },
  {
    id: 3,
    name: "Gaara",
    neighborhood: "Hidden Sand Village",
    age: 32,
    image: "https://i.ibb.co/PTZPtZD/gaara.png",
  },
  {
    id: 4,
    name: "Eren Yeager",
    neighborhood: "Shiganshina District",
    age: 19,
    image: "https://i.ibb.co/9HPSjLv/erenyeager.jpg",
  },
  {
    id: 5,
    name: "Itachi Uchiha",
    neighborhood: "Hidden Leaf Village",
    age: 21,
    image: "https://i.ibb.co/2dZMPws/Itachiuchiha.png",
  },
  {
    id: 6,
    name: "Mikasa Ackerman",
    neighborhood: "Shiganshina District",
    age: 19,
    image: "https://i.ibb.co/N2WH8wB/mikasaackerman.png",
  },
  {
    id: 7,
    name: "Juuzou Suzuya",
    neighborhood: "Tokyo",
    age: 22,
    image: "https://i.ibb.co/48x4nBV/juuzousuzuya.png",
  },
  {
    id: 8,
    name: "Levi Ackerman",
    neighborhood: "Hita City",
    age: 34,
    image: "https://i.ibb.co/8rtSqHW/leviackerman.png",
  },
  {
    id: 9,
    name: "Minato Namikaze",
    neighborhood: "Hidden Leaf Village",
    age: 24,
    image: "https://i.ibb.co/8Mzh0v9/minatonamikaze.jpg",
  },
  {
    id: 10,
    name: "Lord Pain",
    neighborhood: "Hidden Rain Village",
    age: 35,
    image: "https://i.ibb.co/Nnw6PH7/lordpain.png",
  },
  {
    id: 11,
    name: "Monkey D. Luffy",
    neighborhood: "Foosha Village",
    age: 19,
    image: "https://i.ibb.co/Hp77t62/monkeydluffy.png",
  },
  {
    id: 12,
    name: "Naruto Uzumaki",
    neighborhood: "Hidden Leaf Village",
    age: 19,
    image: "https://i.ibb.co/LhjBTxc/narutouzumaki.jpg",
  },
  {
    id: 13,
    name: "Saskue Uchiha",
    neighborhood: "Hidden Leaf Village",
    age: 22,
    image: "https://i.ibb.co/sWRWRrF/saskueuchiha.png",
  },
  {
    id: 14,
    name: "Roronoa Zoro",
    neighborhood: "Shimotsuki",
    age: 21,
    image: "https://i.ibb.co/j47gy3W/roronoazoro.png",
  },
  {
    id: 15,
    name: "Touka Kirishima",
    neighborhood: "Tokyo",
    age: 21,
    image: "https://i.ibb.co/HGWZcFC/toukakirishima.jpg",
  },
  {
    id: 16,
    name: "Satsuki Kiryuin",
    neighborhood: "Honnōji Academy",
    age: 19,
    image: "https://i.ibb.co/SrSLdDk/satsukikiryuin.jpg",
  },
  {
    id: 17,
    name: "Rize Kamishiro",
    neighborhood: "Tokyo",
    age: 18,
    image: "https://i.ibb.co/0ccKtGz/rizekamishiro.png",
  },
  {
    id: 18,
    name: "Kushina Uzumaki",
    neighborhood: "Hidden Leaf Village",
    age: 24,
    image: "https://i.ibb.co/bLCTr8K/kushinauzumaki.png",
  },
  {
    id: 19,
    name: "Nezuko Kamado",
    neighborhood: "Asakusa",
    age: 14,
    image: "https://i.ibb.co/h2ghnTG/nezukokamado.jpg",
  },
  {
    id: 20,
    name: "Tanjiro Kamado",
    neighborhood: "Asakusa",
    age: 17,
    image: "https://i.ibb.co/3yq2fBV/tanjirokamado.jpg",
  },
  {
    id: 21,
    name: "Killua Zoldyck",
    neighborhood: "Padokea",
    age: 12,
    image: "https://i.ibb.co/mF5GRgF/killuazoldyck.png",
  },
  {
    id: 22,
    name: "Sakura Haruno",
    neighborhood: "Hidden Leaf Village",
    age: 33,
    image: "https://i.ibb.co/RyZP7Jj/sakuraharuno.jpg",
  },
  {
    id: 23,
    name: "Lady Tsunade",
    neighborhood: "Hidden Leaf Village",
    age: 50,
    image: "https://i.ibb.co/d6pQ4Cr/ladytsunade.png",
  },
  {
    id: 24,
    name: "Ino Yamanaka",
    neighborhood: "Hidden Leaf Village",
    age: 17,
    image: "https://i.ibb.co/ZgQR5Gf/inoyamanaka.jpg",
  },
  {
    id: 25,
    name: "Hinata Hyuga",
    neighborhood: "Hidden Leaf Village",
    age: 16,
    image: "https://i.ibb.co/6gCx3cK/hinatahyuga.jpg",
  },
];

export const suggestions = [
  "Don't be shy.",
  "Nobody's perfect.",
  "Celebrate the small stuff.",
  "Do what makes you happy.",
  "Focus on what you can change.",
  "Remember that everyone makes mistakes.",
  "Get movin'",
  "You do you.",
  "Be nice to yourself.",
  "Being your own best cheerleader. Telling yourself, 'I've got this!!'",
  "Remembering to take care of myself.",
  "Not pretending to be something I’m not.",
  "I trust myself and my inner guidance!",
  "I remember a time I took a risk and was/am happy about the outcome.",
  "Remind myself of the moments I have been proud of myself.",
  "A smile and awareness of posture--lengthening my spine rather than slumping!",
  "Putting on a great pair of boots makes me feel confident to kick butt.",
  "I feel better when I am wearing a pair of beaded earrings that I made.",
  "I wear the color orange. It's my power color!!",
  "Wearing an outfit that makes me look good.",
  "For me it’s red lipstick. Makes me feel powerful.",
  "A great pair of heels can do wonders... until my feet start to hurt.",
];
