export const characters = [
  {
    id: 1,
    name: "Ryuko Matoi",
    neighborhood: "Honnōji Academy",
    age: 17,
    image: "images/ryukomatoi.jpg",
  },
  {
    id: 2,
    name: "Ann Takamaki",
    neighborhood: "Yongen-Jaya",
    age: 16,
    image: "images/anntakamaki.jpg",
  },
  {
    id: 3,
    name: "Gaara",
    neighborhood: "Hidden Sand Village",
    age: 32,
    image: "images/gaara.png",
  },
  {
    id: 4,
    name: "Eren Yeager",
    neighborhood: "Shiganshina District",
    age: 19,
    image: "images/erenyeager.jpg",
  },
  {
    id: 5,
    name: "Itachi Uchiha",
    neighborhood: "Hidden Leaf Village",
    age: 21,
    image: "images/Itachiuchiha.png",
  },
  {
    id: 6,
    name: "Mikasa Ackerman",
    neighborhood: "Shiganshina District",
    age: 19,
    image: "images/mikasaackerman.png",
  },
  {
    id: 7,
    name: "Juuzou Suzuya",
    neighborhood: "Tokyo",
    age: 22,
    image: "images/juuzousuzuya.png",
  },
  {
    id: 8,
    name: "Levi Ackerman",
    neighborhood: "Hita City",
    age: 34,
    image: "images/leviackerman.png",
  },
  {
    id: 9,
    name: "Minato Namikaze",
    neighborhood: "Hidden Leaf Village",
    age: 24,
    image: "images/minatonamikaze.jpg",
  },
  {
    id: 10,
    name: "Lord Pain",
    neighborhood: "Hidden Rain Village",
    age: 35,
    image: "images/lordpain.png",
  },
  {
    id: 11,
    name: "Monkey D. Luffy",
    neighborhood: "Foosha Village",
    age: 19,
    image: "images/monkeydluffy.png",
  },
  {
    id: 12,
    name: "Naruto Uzumaki",
    neighborhood: "Hidden Leaf Village",
    age: 19,
    image: "images/narutouzumaki.jpg",
  },
  {
    id: 13,
    name: "Saskue Uchiha",
    neighborhood: "Hidden Leaf Village",
    age: 22,
    image: "images/saskueuchiha.png",
  },
  {
    id: 14,
    name: "Roronoa Zoro",
    neighborhood: "Shimotsuki",
    age: 21,
    image: "images/roronoazoro.png",
  },
  {
    id: 15,
    name: "Touka Kirishima",
    neighborhood: "Tokyo",
    age: 21,
    image: "images/toukakirishima.jpg",
  },
  {
    id: 16,
    name: "Satsuki Kiryuin",
    neighborhood: "Honnōji Academy",
    age: 19,
    image: "images/satsukikiryuin.jpg",
  },
  {
    id: 17,
    name: "Rize Kamishiro",
    neighborhood: "Tokyo",
    age: 18,
    image: "images/rizekamishiro.png",
  },
  {
    id: 18,
    name: "Biscuit Krueger",
    neighborhood: "Aiai, the City of Love",
    age: 57,
    image: "images/biscuitkrueger.jpg",
  },
  {
    id: 19,
    name: "Nezuko Kamado",
    neighborhood: "Asakusa",
    age: 14,
    image: "images/nezukokamado.jpg",
  },
  {
    id: 20,
    name: "Tanjiro Kamado",
    neighborhood: "Asakusa",
    age: 17,
    image: "images/tanjirokamado.jpg",
  },
  {
    id: 21,
    name: "Killua Zoldyck",
    neighborhood: "Padokea",
    age: 12,
    image: "images/killuazoldyck.png",
  },
  {
    id: 22,
    name: "Sakura Haruno",
    neighborhood: "Hidden Leaf Village",
    age: 33,
    image: "images/sakuraharuno.jpg",
  },
  {
    id: 23,
    name: "Lady Tsunade",
    neighborhood: "Hidden Leaf Village",
    age: 50,
    image: "images/ladytsunade.png",
  },
  {
    id: 24,
    name: "Ino Yamanaka",
    neighborhood: "Hidden Leaf Village",
    age: 17,
    image: "images/inoyamanaka.jpg",
  },
  {
    id: 25,
    name: "Hinata Hyuga",
    neighborhood: "Hidden Leaf Village",
    age: 16,
    image: "images/hinatahyuga.jpg",
  },
  {
    id: 26,
    name: "Gon Freecss",
    neighborhood: "Whale Island",
    age: 12,
    image: "images/gonfreecss.jpg",
  },
  {
    id: 27,
    name: "Jiraiya",
    neighborhood: "Hidden Leaf Village",
    age: 54,
    image: "images/jiraiya.png",
  },
  {
    id: 28,
    name: "Ken Kaneki",
    neighborhood: "Tokyo",
    age: 19,
    image: "images/kenkaneki.png",
  },
  {
    id: 29,
    name: "Konan",
    neighborhood: "Hidden Rain Village",
    age: 35,
    image: "images/konan.jpg",
  },
  {
    id: 30,
    name: "Kurapika",
    neighborhood: "Lukso Province",
    age: 18,
    image: "images/kurapika.jpg",
  },
  {
    id: 31,
    name: "Nami",
    neighborhood: "Cocoyasi Village",
    age: 20,
    image: "images/nami.png",
  },
  {
    id: 32,
    name: "Nico Robin",
    neighborhood: "Island of Ohara",
    age: 30,
    image: "images/nicorobin.jpg",
  },
  {
    id: 33,
    name: "Iris Cannary",
    neighborhood: "Kazaly",
    age: 30,
    image: "images/iriscannary.jpg",
  },
  {
    id: 34,
    name: "Futaba Sakura",
    neighborhood: "Yongen-Jaya",
    age: 15,
    image: "images/futabasakura.jpg",
  },
  {
    id: 35,
    name: "Kite",
    neighborhood: "Whale Island",
    age: 28,
    image: "images/kite.jpg",
  },
  {
    id: 36,
    name: "Kurenai Yuhi",
    neighborhood: "Hidden Leaf Village",
    age: 31,
    image: "images/kurenaiyuhi.png",
  },
  {
    id: 37,
    name: "Akame",
    neighborhood: "The Empire",
    age: 16,
    image: "images/akame.png",
  },
  {
    id: 38,
    name: "Akira Mado",
    neighborhood: "Tokyo",
    age: 22,
    image: "images/akiramado.png",
  },
  {
    id: 39,
    name: "Celica Arfonia",
    neighborhood: "Melgalius' Sky Castle",
    age: 400,
    image: "images/celicaarfonia.jpg",
  },
  {
    id: 40,
    name: "Erwin Smith",
    neighborhood: "Honey Grove",
    age: 35,
    image: "images/erwinsmith.jpg",
  },
  {
    id: 41,
    name: "Lucy Heartfilia",
    neighborhood: "Fairy Tail City",
    age: 17,
    image: "images/lucyheartfilia.jpg",
  },
  {
    id: 42,
    name: "Madara Uchiha",
    neighborhood: "Hidden Leaf Village",
    age: 90,
    image: "images/madarauchiha.png",
  },
  {
    id: 43,
    name: "Neferpitou",
    neighborhood: "Chimera Ant",
    age: 0,
    image: "images/neferpitou.png",
  },
  {
    id: 44,
    name: "Obito Uchiha",
    neighborhood: "Hidden Leaf Village",
    age: 13,
    image: "images/obitouchiha.jpg",
  },
  {
    id: 45,
    name: "Reiner Braun",
    neighborhood: "Shiganshina District",
    age: 24,
    image: "images/reinerbraun.png",
  },
  {
    id: 46,
    name: "Rias Gremory",
    neighborhood: "Kuoh Town",
    age: 19,
    image: "images/riasgremory.jpg",
  },
  {
    id: 47,
    name: "Shizuku",
    neighborhood: "Phantom Troupe",
    age: 19,
    image: "images/shizuku.png",
  },
  {
    id: 48,
    name: "Temari",
    neighborhood: "Hidden Sand Village",
    age: 33,
    image: "images/temari.png",
  },
  {
    id: 49,
    name: "Usopp",
    neighborhood: "Syrup Village",
    age: 19,
    image: "images/usopp.jpg",
  },
  {
    id: 50,
    name: "Vinsmoke Sanji",
    neighborhood: "North Blue",
    age: 21,
    image: "images/vinsmokesanji.png",
  },
];

export const suggestions = [
  "Don't be shy.",
  "Nobody's perfect.",
  "Celebrate the small stuff.",
  "Do what makes you happy.",
  "Focus on what you can change.",
  "Remember that everyone makes mistakes.",
  "Get movin'",
  "You do you.",
  "Be nice to yourself.",
  "Being your own best cheerleader. Telling yourself, 'I've got this!!'",
  "Remembering to take care of myself.",
  "Not pretending to be something I’m not.",
  "I trust myself and my inner guidance!",
  "I remember a time I took a risk and was/am happy about the outcome.",
  "Remind myself of the moments I have been proud of myself.",
  "A smile and awareness of posture--lengthening my spine rather than slumping!",
  "Putting on a great pair of boots makes me feel confident to kick butt.",
  "I feel better when I am wearing a pair of beaded earrings that I made.",
  "I wear the color orange. It's my power color!!",
  "Wearing an outfit that makes me look good.",
  "For me it’s red lipstick. Makes me feel powerful.",
  "A great pair of heels can do wonders... until my feet start to hurt.",
  "Be more self confident by stopping negative self talk.",
  "Build lasting self-confidence.",
  "Think more confidently to overcome negativity.",
  "Believe in your capabilities.",
  "Focus on achievements to improve self-confidence.",
  "Understand what gives you self-confidence.",
  "Be true to yourself.",
  "Don’t compare yourself.",
  "Spend time with people who build your self-confidence",
  "Celebrate your achievements every day.",
  "Groom yourself.",
  "Dress nicely.",
  "Photoshop your self-image.",
  "Think positive.",
  "Kill negative thoughts.",
  "Get to know yourself.",
  "Know yourself and you will win all battles. – Sun Tzu",
  "Be kind and generous.",
  "One important key to success is self-confidence. A key to self-confidence is preparation. – Arthur Ashe",
  "Know your principles and live them.",
  "Set a small goal and achieve it.",
  "Empower yourself with knowledge.",
  "What you are thinking about, you are becoming.",
  "What we fear doing most is usually what we most need to do.",
  "Emotion is created by motion.",
  "Putting your hands in your pockets is one of the worst things you can do if you want to appear confident.",
  "Confidence isn’t optimism or pessimism, and it’s not a character attribute. It’s the expectation of a positive outcome.",
  "Confidence is contagious. So is lack of confidence. —Vince Lombardi",
  "Don't be satisfied with stories, how things have gone with others. Unfold your own myth. ―Rumi, The Essential Rumi",
  "The moment you doubt whether you can fly, you cease for ever to be able to do it. ―J. M. Barrie, Peter Pan",
  "We are always the same age inside. ―Gertrude Stein",
  "Believe you can and you're halfway there. ―Theodore Roosevelt",
];
